env:
    DEVICE_CODENAME: rosy
    BUILD_USER: xiaomi
    BUILD_HOST: nfs-projects
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    ANYKERNEL: "https://github.com/NFS-Project/AnyKernel3.git"
    TG_TOKEN: "ENCRYPTED[!d52ab360b3e8517a18c20d86dac6f328c67670b9ed96c668a5871179c40a24f1bd8c92e233558c1beeda79bad6cf316d!]"
    TG_CHAT_ID: "ENCRYPTED[!f1e4e3d269d43632542852d81b136dd2d40e66a0686574e493ddce5d86989830cf6fbac58494c33421c9ecf70dfe3fe8!]"

task:
  name: "Kernel Build.."
  timeout_in: 1h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  Sync_script:
      - ./download.sh

  Build_kernel_Clang_script:
      - ./clang.sh
      - ./done.sh
