env:
    DEVICE_CODENAME: rosy
    BUILD_USER: NFSproject
    BUILD_HOST: NFS86
    KERNEL_SOURCE: https://github.com/AnGgIt88/Xiaomi_Kernel_OpenSource
    KERNEL_BRANCH: riva-n-oss
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    ANYKERNEL: "https://github.com/NFS-Project/AnyKernel3.git"

task:
  name: "Kernel Build.."
  timeout_in: 2h
  container:
      image: anggit86/ubuntu:xenial
      cpu: 8
      memory: 32G

  Sync_script:
      - ./download.sh

  Build_kernel_Clang_script:
      - ./compile.sh
